-- Bootstrap bearer tokens were valid for ever.
--
-- `identities.active` already existed and `authenticate_openppwr_token` already checked it, so a
-- credential *could* be revoked by an operator with database access. What did not exist was any expiry, or
-- any path to rotate a token without editing the table by hand. Bootstrap mints one token per role
-- including `tenant_admin`, so a deployment came up with a privileged credential that never aged out.
--
-- `/v1/logout` already reported this honestly —
-- `STATIC_CREDENTIAL_NOT_REVOCABLE` — so the behaviour was known; that the default included a
-- non-expiring *privileged* credential was not recorded anywhere.
--
-- Session credentials from `/v1/login` were never affected: they expire and are revocable already. This is
-- about the operator-facing bearer tokens only.

-- Ninety days, and existing rows are backfilled from their creation time rather than from now, so an old
-- deployment does not silently gain three fresh months on upgrade.
ALTER TABLE identities
  ADD COLUMN IF NOT EXISTS token_expires_at timestamptz,
  ADD COLUMN IF NOT EXISTS token_rotated_at timestamptz;

UPDATE identities
   SET token_expires_at = created_at + interval '90 days'
 WHERE token_expires_at IS NULL;

ALTER TABLE identities
  ALTER COLUMN token_expires_at SET NOT NULL,
  ALTER COLUMN token_expires_at SET DEFAULT (now() + interval '90 days');

-- Expiry is enforced where authentication happens, not at the call sites. A check that each caller has to
-- remember is a check that one caller will forget.
--
-- The function has two branches, and the expiry belongs to exactly one of them. The first resolves an
-- operator bearer token straight from `identities`; that is the credential this migration is about. The
-- second resolves a session token from `/v1/login`, which already carries its own `expires_at` and
-- `revoked_at` — adding the identity expiry there would retire a live session the moment its identity's
-- operator token aged out, which is a different and unintended behaviour.
--
-- Migration 005 widened the return type to include session columns, so this replaces that definition
-- rather than the original from 001.
DROP FUNCTION IF EXISTS authenticate_openppwr_token(text);

CREATE FUNCTION authenticate_openppwr_token(p_token_hash text)
RETURNS TABLE (tenant_id uuid, actor_id uuid, actor_role text, supplier_id text, session_id uuid, session_expires_at timestamptz)
LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public, pg_temp AS $$
  SELECT i.tenant_id, i.id, i.role, i.supplier_id, NULL::uuid, NULL::timestamptz
  FROM identities i
  WHERE i.token_hash = p_token_hash
    AND i.active = true
    AND i.token_expires_at > now()
  UNION ALL
  SELECT i.tenant_id, i.id, i.role, i.supplier_id, s.id, s.expires_at
  FROM auth_sessions s
  JOIN identities i ON i.tenant_id = s.tenant_id AND i.id = s.identity_id
  WHERE s.token_hash = p_token_hash
    AND s.revoked_at IS NULL
    AND s.expires_at > now()
    AND i.active = true
$$;
REVOKE ALL ON FUNCTION authenticate_openppwr_token(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION authenticate_openppwr_token(text) TO openppwr_app;

-- Rotation, so that fixing an exposed token does not require hand-editing a table.
--
-- Takes the new hash rather than the token: the plaintext is generated by the caller, handed to the
-- operator once, and never travels into the database. The old hash is required as well, so rotating a
-- credential means proving you hold the one being replaced.
CREATE OR REPLACE FUNCTION rotate_openppwr_identity_token(
  p_tenant_id uuid, p_identity_id uuid, p_old_token_hash text, p_new_token_hash text, p_valid_days integer DEFAULT 90
) RETURNS timestamptz
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_expires timestamptz;
BEGIN
  IF p_valid_days IS NULL OR p_valid_days < 1 OR p_valid_days > 365 THEN
    RAISE EXCEPTION 'token validity must be between 1 and 365 days';
  END IF;
  v_expires := now() + make_interval(days => p_valid_days);
  UPDATE identities
     SET token_hash = p_new_token_hash,
         token_expires_at = v_expires,
         token_rotated_at = now()
   WHERE tenant_id = p_tenant_id
     AND id = p_identity_id
     AND token_hash = p_old_token_hash
     AND active = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'identity not found, inactive, or the current token does not match';
  END IF;
  RETURN v_expires;
END $$;

REVOKE ALL ON FUNCTION rotate_openppwr_identity_token(uuid, uuid, text, text, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION rotate_openppwr_identity_token(uuid, uuid, text, text, integer) TO openppwr_app;

-- Revocation without rotation, for the case where a credential must simply stop working.
CREATE OR REPLACE FUNCTION revoke_openppwr_identity_token(p_tenant_id uuid, p_identity_id uuid)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
  UPDATE identities SET active = false WHERE tenant_id = p_tenant_id AND id = p_identity_id AND active = true;
  RETURN FOUND;
END $$;

REVOKE ALL ON FUNCTION revoke_openppwr_identity_token(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION revoke_openppwr_identity_token(uuid, uuid) TO openppwr_app;
