export const SITE_ROUTES=['product','community','enterprise','cloud','connect','regulatory','services','pricing','demo','docs','roadmap','security','trust','partners'];
export const LEGAL_ROUTES=['privacy','terms','cookies','imprint'];

export const commonCopy={
  en:{skipToContent:'Skip to main content',lastUpdated:'Last updated',brand:'OpenPPWR',edition:'Community',nav:'Product navigation',openWorkbench:'Open Community workbench',viewCommunity:'Explore Community',language:'Language',status:'Status',scope:'What this surface provides',boundary:'Commercial boundary',evidence:'Release evidence',routeUnavailable:'Not published yet',routeUnavailableBody:'This page is being prepared and has not been approved for publication. Nothing is hidden from you that is ready to read — it simply is not finished. The rest of the site is complete and available.',routeUnavailableAction:'Back to the product',fiction:'ACME companies, products, suppliers and evidence are fictional and exist only for demonstration and testing.',assurance:'OpenPPWR supports PPWR readiness and packaging compliance processes. It does not certify or guarantee legal compliance.',review:'Human review gate',process:'Community reference process',processNote:'One persisted chain. Exact rule version in, reproducible dossier out.',available:'Available',beta:'Beta',privateBeta:'Private Beta',preview:'Preview',planned:'Planned',regulatoryDependency:'Regulatory dependency',backHome:'OpenPPWR home',legal:'Legal information',legalNotice:'This text has not been reviewed by a lawyer',legalNoticeBody:'The privacy, cookie and company information on this site was written by the people who build OpenPPWR, and no qualified legal counsel has reviewed it. It is published as a starting point and as an honest description of openppwr.eu — it is not legal advice, and it is not a notice you can adopt for an installation of your own. If anything here matters to you, have it reviewed by a lawyer qualified in the law that applies to you before you rely on it.',notFound:'This page does not exist',notFoundBody:'The address you followed does not match any page on this site. It may have been mistyped, or it may be a link from an older version of the site that has since been reorganized. The navigation above reaches everything that is published.'},
  pl:{skipToContent:'Przejdź do treści głównej',lastUpdated:'Ostatnia aktualizacja',brand:'OpenPPWR',edition:'Community',nav:'Nawigacja produktu',openWorkbench:'Otwórz obszar Community',viewCommunity:'Poznaj Community',language:'Język',status:'Status',scope:'Zakres tej części',boundary:'Granica komercyjna',evidence:'Dowody wydania',routeUnavailable:'Jeszcze nieopublikowane',routeUnavailableBody:'Ta strona jest przygotowywana i nie została zatwierdzona do publikacji. Nie ukrywamy przed Tobą niczego, co jest gotowe do przeczytania — ta strona nie została jeszcze ukończona. Pozostała część serwisu jest kompletna i dostępna.',routeUnavailableAction:'Wróć do produktu',fiction:'Firmy, produkty, dostawcy i dowody ACME są fikcyjne i służą wyłącznie demonstracji oraz testom.',assurance:'OpenPPWR wspiera gotowość do PPWR i procesy zgodności opakowań. Nie certyfikuje ani nie gwarantuje zgodności prawnej.',review:'Bramka przeglądu',process:'Proces referencyjny Community',processNote:'Jeden utrwalony łańcuch. Dokładna wersja reguły na wejściu, odtwarzalna dokumentacja na wyjściu.',available:'Dostępne',beta:'Beta',privateBeta:'Private Beta',preview:'Preview',planned:'Planowane',regulatoryDependency:'Zależność regulacyjna',backHome:'Strona główna OpenPPWR',legal:'Informacje prawne',legalNotice:'Ten tekst nie został sprawdzony przez prawnika',legalNoticeBody:'Informacje o prywatności, plikach cookie i danych spółki w tym serwisie przygotował zespół tworzący OpenPPWR i nie sprawdził ich żaden wykwalifikowany prawnik. Publikujemy je jako punkt wyjścia i jako rzetelny opis serwisu openppwr.eu — nie są poradą prawną ani informacją, którą można przejąć dla własnej instalacji. Jeżeli którakolwiek z tych treści ma dla Ciebie znaczenie, przed powołaniem się na nią zleć jej sprawdzenie prawnikowi znającemu prawo właściwe w Twoim przypadku.',notFound:'Ta strona nie istnieje',notFoundBody:'Podany adres nie odpowiada żadnej stronie w tym serwisie. Mógł zostać wpisany błędnie albo pochodzi z odnośnika do wcześniejszej wersji serwisu, która została przebudowana. Nawigacja powyżej prowadzi do wszystkich opublikowanych stron.'},
  de:{skipToContent:'Zum Hauptinhalt springen',lastUpdated:'Zuletzt aktualisiert',brand:'OpenPPWR',edition:'Community',nav:'Produktnavigation',openWorkbench:'Community-Arbeitsbereich öffnen',viewCommunity:'Community ansehen',language:'Sprache',status:'Status',scope:'Leistungsumfang dieser Seite',boundary:'Kommerzielle Abgrenzung',evidence:'Release-Nachweise',routeUnavailable:'Noch nicht veröffentlicht',routeUnavailableBody:'Diese Seite wird vorbereitet und ist noch nicht zur Veröffentlichung freigegeben. Es wird Ihnen nichts vorenthalten, was lesbar wäre — es ist schlicht noch nicht fertig. Der übrige Teil der Website ist vollständig und verfügbar.',routeUnavailableAction:'Zurück zum Produkt',fiction:'ACME-Unternehmen, Produkte, Lieferanten und Nachweise sind fiktiv und dienen ausschließlich Demonstrations- und Testzwecken.',assurance:'OpenPPWR unterstützt PPWR-Bereitschaft und Verpackungs-Compliance-Prozesse. Es zertifiziert oder garantiert keine Rechtskonformität.',review:'Prüffreigabe',process:'Community-Referenzprozess',processNote:'Eine persistierte Kette. Exakte Regelversion hinein, reproduzierbares Dossier heraus.',available:'Verfügbar',beta:'Beta',privateBeta:'Private Beta',preview:'Vorschau',planned:'Geplant',regulatoryDependency:'Regulatorische Abhängigkeit',backHome:'OpenPPWR Startseite',legal:'Rechtliche Informationen',legalNotice:'Dieser Text wurde nicht anwaltlich geprüft',legalNoticeBody:'Die Datenschutz-, Cookie- und Unternehmensangaben auf dieser Website stammen von dem Team, das OpenPPWR entwickelt; eine qualifizierte Rechtsberatung hat sie nicht geprüft. Wir veröffentlichen sie als Ausgangspunkt und als wahrheitsgemäße Beschreibung von openppwr.eu — sie sind keine Rechtsberatung und keine Erklärung, die Sie für eine eigene Installation übernehmen können. Wenn hier etwas für Sie zählt, lassen Sie es anwaltlich prüfen, und zwar nach dem für Sie geltenden Recht, bevor Sie sich darauf verlassen.',notFound:'Diese Seite existiert nicht',notFoundBody:'Die aufgerufene Adresse entspricht keiner Seite dieser Website. Möglicherweise wurde sie falsch eingegeben, oder sie stammt aus einem Verweis auf eine frühere Fassung der Website, die inzwischen umstrukturiert wurde. Die Navigation oben führt zu allen veröffentlichten Seiten.'},
};

const en={
  home:{eyebrow:'Packaging evidence, decisions, dossier',title:'Make packaging readiness reproducible.',summary:'OpenPPWR Community connects packaging data, supplier evidence, versioned assessments, remediation and review artifacts in one self-hosted workflow.',points:['Real PostgreSQL transactions and FORCE RLS','Four explainable outcomes, never a hard-coded pass','Frozen JSON, PDF and ZIP dossier with SHA-256 manifest'],status:'beta'},
  product:{eyebrow:'One evidence chain',title:'From packaging records to review-ready evidence.',summary:'OpenPPWR keeps data, rule versions, evidence decisions, gaps and dossier outputs connected so a reviewer can reconstruct what happened.',points:['CSV and JSON packaging import','Quarantined evidence and authorized review','Assessment, remediation, reassessment and audit reconstruction'],status:'beta'},
  community:{eyebrow:'Apache-2.0 self-hosted core',title:'Useful Community software, not a restricted shell.',summary:'Community contains the complete ACME reference workflow and public deployment automation. Commercial services remain separate.',points:['Self-hosted API, worker, web and PostgreSQL','Transparent demonstration rule pack','Public SDK and integration-contract boundary'],status:'beta'},
  enterprise:{eyebrow:'Commercial boundary',title:'Enterprise controls follow Community adoption.',summary:'Advanced identity, deployment controls and enterprise support are separate commercial capabilities. They are not included in this beta.',points:['Advanced SSO, SCIM and governance','Private deployment options and support','Separate commercial agreement'],status:'planned'},
  cloud:{eyebrow:'Managed OpenPPWR',title:'Cloud operations are Private Beta.',summary:'OpenPPWR Cloud is the paid managed deployment and operations model. Self-service provisioning and billing are not available in this release.',points:['Manual onboarding during Private Beta','Commercial SaaS terms, DPA and SLA required','Community release does not depend on Cloud automation'],status:'privateBeta'},
  connect:{eyebrow:'Commercial integrations',title:'Connect starts with SAP, after Community.',summary:'Public contracts may be Apache-2.0. Production ERP connector implementations remain separate commercial modules and services.',points:['SAP integration direction defined','Additional ERP connectors planned later','No production connector claimed in Community beta'],status:'planned'},
  regulatory:{eyebrow:'Maintained rule content',title:'Regulatory subscriptions stay separate.',summary:'Community includes a small transparent demonstration rule. Maintained regulatory content and updates are commercial and require qualified review.',points:['Exact rule version retained in every assessment','Community demonstration content is non-authoritative','German regulatory wording still requires human review'],status:'regulatoryDependency'},
  services:{eyebrow:'Implementation help',title:'Assessment, QuickStart and delivery support.',summary:'Attentus services can help teams assess data, install Community and design integrations without placing customer material in the public repository.',points:['Readiness assessment and Design Partner work','QuickStart, migration and training','Commercial implementation and support'],status:'available'},
  pricing:{eyebrow:'Transparent product boundary',title:'Community is open. Managed work is commercial.',summary:'Community source uses Apache-2.0. Cloud, Connect, Regulatory, Enterprise and professional services require a proposal or separate agreement.',points:['Community: self-hosted, Apache-2.0','Commercial offers: scoped and contracted separately','No invented public price or binding offer'],status:'preview'},
  demo:{eyebrow:'Synthetic ACME only',title:'The demonstration runs on fictional ACME data.',summary:'The reference journey uses invented ACME records from end to end. The demonstration we host at openppwr.eu is access-controlled rather than open to anonymous visitors; a demonstration you stand up yourself is yours to protect.',points:['Resettable synthetic tenant','Upload and abuse controls before any open access','Access to the openppwr.eu demonstration is arranged individually'],status:'privateBeta'},
  docs:{eyebrow:'Operate what is documented',title:'Install, verify, recover and understand.',summary:'Community documentation covers the real workflow and its operating boundaries. Unsupported platforms and unfinished gates stay clearly marked.',points:['QuickStart and Debian 13 installer','Backup, restore, upgrade and rollback','API, architecture, security and known limitations'],status:'beta'},
  roadmap:{eyebrow:'Community first',title:'Finish one complete public workflow before expansion.',summary:'Current critical path is private deployment, clean-server installer, human reviews and publication evidence. Commercial expansion follows.',points:['Community beta release','Hardening and reviewer feedback','Cloud, Connect and Regulatory work after release'],status:'available'},
  security:{eyebrow:'Fail closed',title:'Identity, tenant isolation and evidence integrity.',summary:'Verified bearer identity, FORCE RLS, private evidence storage, ClamAV scanning and audit reconstruction define the Community security model.',points:['No client-supplied tenant or actor headers','Integrity checked before scan and download','Responsible disclosure through SECURITY.md'],status:'beta'},
  trust:{eyebrow:'Evidence over promises',title:'Know what passed, what remains and who must review.',summary:'Release reports separate automated engineering proof from human, legal and operational approval.',points:['Exact source SHA and immutable image tag','SBOM and vulnerability/configuration scans','Known limitations published without assurance claims'],status:'preview'},
  partners:{eyebrow:'Ecosystem after stable core',title:'Partner program is planned, not launched.',summary:'Implementation and regulatory partners may extend adoption later. No certification or partner status is offered in this beta.',points:['Integration partners planned','Qualified regulatory review remains independent','Trademark use follows TRADEMARKS.md'],status:'planned'},
  privacy:{title:'Privacy notice',summary:'What we process, why, and what we do not. Self-hosted Community sends us nothing at all.'},
  terms:{title:'Terms of use',summary:'Terms for this website and the demonstration environment. The software itself is licensed under Apache-2.0.'},
  cookies:{title:'Cookie notice',summary:'No analytics and no tracking. Strictly necessary cookies only, disclosed in full.'},
  imprint:{title:'Company information',summary:'Legal entity, registered address, register details and contact channels for OpenPPWR.'},
};

const pl={
  home:{eyebrow:'Dowody opakowań, decyzje, dokumentacja',title:'Odtwarzalna gotowość opakowań.',summary:'OpenPPWR Community łączy dane opakowań, dowody dostawców, wersjonowane oceny, działania naprawcze i artefakty przeglądu w jednym procesie self-hosted.',points:['Rzeczywiste transakcje PostgreSQL i FORCE RLS','Cztery wyjaśnialne wyniki, bez zaszytego PASS','Zamrożona dokumentacja JSON, PDF i ZIP z manifestem SHA-256'],status:'beta'},
  product:{eyebrow:'Jeden łańcuch dowodowy',title:'Od danych opakowań do gotowego przeglądu.',summary:'OpenPPWR zachowuje powiązania danych, wersji reguł, decyzji dowodowych, luk i dokumentacji, aby umożliwić rekonstrukcję procesu.',points:['Import opakowań CSV i JSON','Kwarantanna oraz autoryzowany przegląd dowodów','Ocena, działania naprawcze, ponowna ocena i audyt'],status:'beta'},
  community:{eyebrow:'Rdzeń self-hosted Apache-2.0',title:'Użyteczne Community, nie ograniczona atrapa.',summary:'Community zawiera kompletny proces referencyjny ACME i publiczną automatyzację wdrożenia. Usługi komercyjne pozostają osobno.',points:['Self-hosted API, worker, web i PostgreSQL','Przejrzysty demonstracyjny pakiet reguł','Publiczna granica SDK i kontraktów integracyjnych'],status:'beta'},
  enterprise:{eyebrow:'Granica komercyjna',title:'Kontrole Enterprise po wydaniu Community.',summary:'Zaawansowana tożsamość, kontrola wdrożeń i wsparcie Enterprise są osobnymi funkcjami komercyjnymi. Nie są dostępne w tej becie.',points:['Zaawansowane SSO, SCIM i governance','Prywatne opcje wdrożenia i wsparcie','Osobna umowa komercyjna'],status:'planned'},
  cloud:{eyebrow:'Zarządzany OpenPPWR',title:'Cloud ma status Private Beta.',summary:'OpenPPWR Cloud to płatny model zarządzanego wdrożenia i utrzymania. Samoobsługowe provisionowanie i billing nie są dostępne.',points:['Ręczny onboarding w Private Beta','Wymagane SaaS terms, DPA i SLA','Automatyzacja Cloud nie blokuje Community'],status:'privateBeta'},
  connect:{eyebrow:'Integracje komercyjne',title:'Connect zaczyna od SAP po Community.',summary:'Publiczne kontrakty mogą być Apache-2.0. Produkcyjne implementacje konektorów ERP pozostają osobnymi modułami i usługami komercyjnymi.',points:['Określony kierunek integracji SAP','Kolejne ERP planowane później','Brak deklaracji produkcyjnego konektora w Community beta'],status:'planned'},
  regulatory:{eyebrow:'Utrzymywane treści reguł',title:'Subskrypcje Regulatory pozostają osobno.',summary:'Community zawiera małą, przejrzystą regułę demonstracyjną. Utrzymywane treści i aktualizacje są komercyjne i wymagają kwalifikowanego przeglądu.',points:['Każda ocena zachowuje dokładną wersję reguły','Treść demonstracyjna nie jest autorytatywna','Niemieckie sformułowania wymagają przeglądu człowieka'],status:'regulatoryDependency'},
  services:{eyebrow:'Wsparcie wdrożenia',title:'Assessment, QuickStart i pomoc realizacyjna.',summary:'Usługi Attentus wspierają ocenę danych, instalację Community i projekt integracji bez umieszczania materiałów klienta w publicznym repozytorium.',points:['Readiness assessment i Design Partner','QuickStart, migracja i szkolenia','Komercyjne wdrożenie i wsparcie'],status:'available'},
  pricing:{eyebrow:'Czytelna granica produktu',title:'Community jest otwarte. Usługi zarządzane są komercyjne.',summary:'Kod Community używa Apache-2.0. Cloud, Connect, Regulatory, Enterprise i usługi profesjonalne wymagają oferty lub osobnej umowy.',points:['Community: self-hosted, Apache-2.0','Oferty komercyjne: osobny zakres i umowa','Brak zmyślonego cennika lub wiążącej oferty'],status:'preview'},
  demo:{eyebrow:'Wyłącznie syntetyczne ACME',title:'Demonstracja działa na fikcyjnych danych ACME.',summary:'Proces referencyjny opiera się w całości na wymyślonych rekordach ACME. Demonstracja prowadzona przez nas pod openppwr.eu jest objęta kontrolą dostępu, a nie otwarta dla anonimowych odwiedzających; demonstrację uruchomioną samodzielnie zabezpiecza jej własny operator.',points:['Resetowalny syntetyczny tenant','Zabezpieczenia uploadu i nadużyć przed otwarciem dostępu','Dostęp do demonstracji pod openppwr.eu jest uzgadniany indywidualnie'],status:'privateBeta'},
  docs:{eyebrow:'Obsługuj zgodnie z dokumentacją',title:'Instaluj, weryfikuj, odtwarzaj i rozumiej.',summary:'Dokumentacja Community opisuje prawdziwy proces i granice operacyjne. Nieprzetestowane platformy i otwarte bramki pozostają oznaczone.',points:['QuickStart i instalator Debian 13','Backup, restore, upgrade i rollback','API, architektura, bezpieczeństwo i ograniczenia'],status:'beta'},
  roadmap:{eyebrow:'Najpierw Community',title:'Najpierw jeden kompletny proces publiczny.',summary:'Ścieżka krytyczna obejmuje prywatne wdrożenie, instalator czystego serwera, przeglądy ludzkie i dowody publikacji.',points:['Wydanie Community beta','Hardening i poprawki z review','Cloud, Connect i Regulatory po wydaniu'],status:'available'},
  security:{eyebrow:'Fail closed',title:'Tożsamość, izolacja tenantów i integralność dowodów.',summary:'Zweryfikowana tożsamość bearer, FORCE RLS, prywatny storage, ClamAV i rekonstrukcja audytu tworzą model bezpieczeństwa Community.',points:['Brak zaufania do nagłówków tenant/actor klienta','Integralność sprawdzana przed skanem i pobraniem','Zgłoszenia podatności przez SECURITY.md'],status:'beta'},
  trust:{eyebrow:'Dowody zamiast obietnic',title:'Wiadomo co przeszło, co zostało i kto zatwierdza.',summary:'Raporty wydania oddzielają automatyczne dowody inżynierskie od zatwierdzeń ludzkich, prawnych i operacyjnych.',points:['Dokładny SHA źródła i niezmienny tag obrazu','SBOM oraz skany podatności i konfiguracji','Publiczne ograniczenia bez obietnic zgodności'],status:'preview'},
  partners:{eyebrow:'Ekosystem po stabilnym rdzeniu',title:'Program partnerski jest planowany.',summary:'Partnerzy wdrożeniowi i regulacyjni mogą później wspierać adopcję. Beta nie oferuje certyfikacji ani statusu partnera.',points:['Planowani partnerzy integracyjni','Kwalifikowany review regulacyjny pozostaje niezależny','Użycie znaku zgodnie z TRADEMARKS.md'],status:'planned'},
  privacy:{title:'Informacja o prywatności',summary:'Co przetwarzamy, po co i czego nie robimy. Self-hosted Community nie wysyła do nas niczego.'},
  terms:{title:'Warunki korzystania',summary:'Warunki dla tej strony i środowiska demonstracyjnego. Samo oprogramowanie jest licencjonowane na Apache-2.0.'},
  cookies:{title:'Informacja o cookies',summary:'Brak analityki i śledzenia. Wyłącznie ciasteczka ściśle niezbędne, ujawnione w całości.'},
  imprint:{title:'Informacje o firmie',summary:'Podmiot prawny, adres siedziby, dane rejestrowe i kanały kontaktu dla OpenPPWR.'},
};

const de={
  home:{eyebrow:'Verpackungsnachweise, Entscheidungen, Dossier',title:'Verpackungsbereitschaft reproduzierbar machen.',summary:'OpenPPWR Community verbindet Verpackungsdaten, Lieferantennachweise, versionierte Bewertungen, Abhilfe und Review-Artefakte in einem selbst gehosteten Ablauf.',points:['Echte PostgreSQL-Transaktionen und FORCE RLS','Vier erklärbare Ergebnisse, kein fest codiertes PASS','Eingefrorenes JSON-, PDF- und ZIP-Dossier mit SHA-256-Manifest'],status:'beta'},
  product:{eyebrow:'Eine Nachweiskette',title:'Von Verpackungsdaten zum prüfbereiten Stand.',summary:'OpenPPWR verknüpft Daten, Regelversionen, Nachweisentscheidungen, Lücken und Dossierausgaben für eine nachvollziehbare Rekonstruktion.',points:['CSV- und JSON-Verpackungsimport','Quarantäne und autorisierte Nachweisprüfung','Bewertung, Abhilfe, Neubewertung und Audit-Rekonstruktion'],status:'beta'},
  community:{eyebrow:'Apache-2.0 Self-hosted Core',title:'Nützliche Community-Software, keine leere Hülle.',summary:'Community enthält den vollständigen ACME-Referenzablauf und öffentliche Deployment-Automatisierung. Kommerzielle Dienste bleiben getrennt.',points:['Self-hosted API, Worker, Web und PostgreSQL','Transparentes Demonstrationsregelwerk','Öffentliche Grenze für SDK und Integrationsverträge'],status:'beta'},
  enterprise:{eyebrow:'Kommerzielle Grenze',title:'Enterprise-Kontrollen folgen nach Community.',summary:'Erweiterte Identität, Deployment-Kontrollen und Enterprise-Support sind separate kommerzielle Fähigkeiten und in dieser Beta nicht verfügbar.',points:['Erweitertes SSO, SCIM und Governance','Private Deployment-Optionen und Support','Separate kommerzielle Vereinbarung'],status:'planned'},
  cloud:{eyebrow:'Managed OpenPPWR',title:'Cloud ist Private Beta.',summary:'OpenPPWR Cloud ist das kostenpflichtige Betriebsmodell. Self-Service-Bereitstellung und Abrechnung sind in diesem Release nicht verfügbar.',points:['Manuelles Onboarding in Private Beta','SaaS-Bedingungen, DPA und SLA erforderlich','Cloud-Automatisierung blockiert Community nicht'],status:'privateBeta'},
  connect:{eyebrow:'Kommerzielle Integrationen',title:'Connect beginnt nach Community mit SAP.',summary:'Öffentliche Verträge können Apache-2.0 sein. Produktive ERP-Connectoren bleiben separate kommerzielle Module und Dienste.',points:['SAP-Integrationsrichtung definiert','Weitere ERP-Systeme später geplant','Kein produktiver Connector in Community Beta behauptet'],status:'planned'},
  regulatory:{eyebrow:'Gepflegte Regelinhalte',title:'Regulatory-Abonnements bleiben getrennt.',summary:'Community enthält eine kleine transparente Demonstrationsregel. Gepflegte Inhalte und Updates sind kommerziell und prüfpflichtig.',points:['Jede Bewertung bewahrt die genaue Regelversion','Demonstrationsinhalt ist nicht rechtsverbindlich','Deutsche regulatorische Formulierungen benötigen Human Review'],status:'regulatoryDependency'},
  services:{eyebrow:'Umsetzungshilfe',title:'Assessment, QuickStart und Delivery-Support.',summary:'Attentus unterstützt Datenbewertung, Community-Installation und Integrationsdesign ohne Kundenmaterial im öffentlichen Repository.',points:['Readiness Assessment und Design Partner','QuickStart, Migration und Training','Kommerzielle Implementierung und Support'],status:'available'},
  pricing:{eyebrow:'Klare Produktgrenze',title:'Community ist offen. Managed Services sind kommerziell.',summary:'Community-Quellcode nutzt Apache-2.0. Cloud, Connect, Regulatory, Enterprise und Services benötigen Angebot oder separate Vereinbarung.',points:['Community: self-hosted, Apache-2.0','Kommerzielle Angebote: separat vereinbart','Keine erfundene Preisliste oder bindendes Angebot'],status:'preview'},
  demo:{eyebrow:'Nur synthetische ACME-Daten',title:'Die Demonstration läuft auf fiktiven ACME-Daten.',summary:'Der Referenzablauf stützt sich durchgehend auf erfundene ACME-Datensätze. Die von uns unter openppwr.eu betriebene Demonstration ist zugangsbeschränkt und nicht anonym erreichbar; eine selbst aufgesetzte Demonstration schützt ihr eigener Betreiber.',points:['Zurücksetzbarer synthetischer Tenant','Upload- und Missbrauchsschutz vor jeder Öffnung','Der Zugang zur Demonstration unter openppwr.eu wird individuell vereinbart'],status:'privateBeta'},
  docs:{eyebrow:'Nur dokumentierten Betrieb versprechen',title:'Installieren, prüfen, wiederherstellen, verstehen.',summary:'Community-Dokumentation beschreibt den realen Ablauf und Betriebsgrenzen. Ungetestete Plattformen und offene Gates bleiben markiert.',points:['QuickStart und Debian-13-Installer','Backup, Restore, Upgrade und Rollback','API, Architektur, Sicherheit und Einschränkungen'],status:'beta'},
  roadmap:{eyebrow:'Community zuerst',title:'Erst einen vollständigen öffentlichen Ablauf liefern.',summary:'Kritischer Pfad: privates Deployment, Clean-Server-Installer, Human Reviews und Publikationsnachweise.',points:['Community-Beta-Release','Hardening und Review-Korrekturen','Cloud, Connect und Regulatory nach Release'],status:'available'},
  security:{eyebrow:'Fail closed',title:'Identität, Tenant-Isolation und Nachweisintegrität.',summary:'Verifizierte Bearer-Identität, FORCE RLS, privater Speicher, ClamAV und Audit-Rekonstruktion definieren das Sicherheitsmodell.',points:['Keine Client-Header für Tenant oder Actor','Integrität vor Scan und Download geprüft','Schwachstellenmeldung über SECURITY.md'],status:'beta'},
  trust:{eyebrow:'Nachweise statt Versprechen',title:'Erkennbar: bestanden, offen, freigabepflichtig.',summary:'Release-Berichte trennen automatisierte Engineering-Nachweise von menschlicher, rechtlicher und betrieblicher Freigabe.',points:['Exakter Source-SHA und unveränderliches Image-Tag','SBOM und Vulnerability-/Konfigurationsscans','Bekannte Einschränkungen ohne Compliance-Garantie'],status:'preview'},
  partners:{eyebrow:'Ökosystem nach stabilem Core',title:'Partnerprogramm ist geplant, nicht gestartet.',summary:'Implementierungs- und Regulatory-Partner können später unterstützen. Diese Beta bietet keine Zertifizierung oder Partnerstufe.',points:['Integrationspartner geplant','Qualifiziertes Regulatory Review bleibt unabhängig','Markennutzung gemäß TRADEMARKS.md'],status:'planned'},
  privacy:{title:'Datenschutzhinweis',summary:'Was wir verarbeiten, wozu und was nicht. Selbst gehostetes Community sendet uns überhaupt nichts.'},
  terms:{title:'Nutzungsbedingungen',summary:'Bedingungen für diese Website und die Demonstrationsumgebung. Die Software selbst steht unter Apache-2.0.'},
  cookies:{title:'Cookie-Hinweis',summary:'Keine Analytik und kein Tracking. Ausschließlich unbedingt erforderliche Cookies, vollständig offengelegt.'},
  imprint:{title:'Unternehmensangaben',summary:'Rechtsträger, Anschrift, Registerangaben und Kontaktwege für OpenPPWR.'},
};

export const pageCopy={en,pl,de};

export const processSteps={
  en:['Install and create ACME tenant','Import and validate packaging','Persist materials, components, BOM and suppliers','Derive exact-version evidence requirements','Quarantine, scan and review evidence','Assess into four outcomes','Assign remediation and reassess','Reach READY_FOR_REVIEW','Freeze and generate dossier','Verify checksums and audit chain'],
  pl:['Zainstaluj i utwórz tenant ACME','Importuj i waliduj opakowania','Zapisz materiały, komponenty, BOM i dostawców','Wyprowadź wymagania dowodowe z wersji reguły','Kwarantanna, skan i przegląd dowodów','Oceń do czterech wyników','Przypisz działania i oceń ponownie','Osiągnij READY_FOR_REVIEW','Zamroź i wygeneruj dokumentację','Sprawdź sumy i łańcuch audytu'],
  de:['Installieren und ACME-Tenant anlegen','Verpackungen importieren und validieren','Materialien, Komponenten, BOM und Lieferanten speichern','Nachweise aus exakter Regelversion ableiten','Nachweise quarantänisieren, scannen und prüfen','Vier Bewertungsergebnisse erzeugen','Abhilfe zuweisen und neu bewerten','READY_FOR_REVIEW erreichen','Snapshot einfrieren und Dossier erzeugen','Prüfsummen und Audit-Kette verifizieren'],
};

export function siteLocale(locale){return ['en','pl','de'].includes(locale)?locale:'en';}
export function siteCommon(locale,key){const normalized=siteLocale(locale);return commonCopy[normalized][key]??commonCopy.en[key]??key;}
export function sitePage(locale,route){const normalized=siteLocale(locale);return pageCopy[normalized][route]??pageCopy.en[route]??pageCopy.en.home;}

// Heading above each page's key points, in the page's own terms.
//
// Every page used to render one generic heading here, which told a reader nothing and made
// seventeen pages read as one template with the words swapped.
export const scopeHeadings={
  en:{home:'What the product does',product:'What the evidence chain holds',community:'What you get when you self-host',enterprise:'What Enterprise adds',cloud:'What managed operation covers',connect:'Where integration stands today',regulatory:'How rule content is controlled',services:'What we can help with',pricing:'How the commercial boundary works',demo:'What the demonstration shows',docs:'What the documentation covers',roadmap:'How we decide what comes next',security:'Controls that are actually in place',trust:'What you can inspect yourself',partners:'How the programme works'},
  pl:{home:'Co robi produkt',product:'Co zawiera łańcuch dowodowy',community:'Co dostajesz przy self-hostingu',enterprise:'Co dodaje Enterprise',cloud:'Co obejmuje usługa zarządzana',connect:'Na jakim etapie są integracje',regulatory:'Jak kontrolowana jest treść reguł',services:'W czym możemy pomóc',pricing:'Jak działa granica komercyjna',demo:'Co pokazuje demonstracja',docs:'Co obejmuje dokumentacja',roadmap:'Jak decydujemy o kolejnych krokach',security:'Kontrole, które faktycznie działają',trust:'Co możesz sprawdzić samodzielnie',partners:'Jak działa program'},
  de:{home:'Was das Produkt leistet',product:'Was die Nachweiskette enthält',community:'Was Sie beim Selbst-Hosten erhalten',enterprise:'Was Enterprise ergänzt',cloud:'Was der Managed-Betrieb abdeckt',connect:'Wo die Integration heute steht',regulatory:'Wie Regelinhalte kontrolliert werden',services:'Wobei wir unterstützen',pricing:'Wie die kommerzielle Abgrenzung funktioniert',demo:'Was die Demonstration zeigt',docs:'Was die Dokumentation abdeckt',roadmap:'Wie wir über die nächsten Schritte entscheiden',security:'Tatsächlich vorhandene Kontrollen',trust:'Was Sie selbst prüfen können',partners:'Wie das Programm funktioniert'},
};

export function scopeHeading(locale,route,fallback){
  return scopeHeadings[locale]?.[route]??scopeHeadings.en[route]??fallback;
}
