export const ACME_DISCLAIMER = 'All companies, products, materials, suppliers and documents in this environment are fictional and generated exclusively for demonstration and testing.';

// Printed on every generated sample document so a file cannot be mistaken for a real one
// once it has been downloaded and separated from this environment.
export const ACME_FICTION_MARKER = 'FICTIONAL ACME SAMPLE — NOT A REAL COMPLIANCE DOCUMENT';

// The dataset is generated by pure functions from these constants, with no randomness,
// clock or environment input, so the same version always produces byte-identical output.
export const ACME_DATASET = { seed: 'ACME-EU-DEMO', schemaVersion: '1.0', generatorVersion: '1.0.0', tenant: 'ACME-EU-DEMO' };

// Reserved example.* domains only (RFC 2606), never a routable address.
export const acmeOrganizations = [
  { id: 'ACME-ORG-001', name: 'ACME Packaging Europe GmbH', role: 'producer', country: 'DE', locale: 'de', address: 'Beispielstrasse 1, 10115 Berlin, Germany', site: 'Berlin plant', contact: 'compliance@acme-eu.example', fictional: true },
  { id: 'ACME-ORG-002', name: 'ACME Packaging Polska Sp. z o.o.', role: 'producer', country: 'PL', locale: 'pl', address: 'ul. Przykladowa 2, 61-001 Poznan, Poland', site: 'Poznan warehouse', contact: 'zgodnosc@acme-pl.example', fictional: true },
  { id: 'ACME-ORG-003', name: 'ACME Distribution France SAS', role: 'distributor', country: 'FR', locale: 'en', address: '3 rue Exemple, 75001 Paris, France', site: 'Paris distribution centre', contact: 'compliance@acme-fr.example', fictional: true },
  { id: 'ACME-ORG-004', name: 'ACME Retail Czechia s.r.o.', role: 'retailer', country: 'CZ', locale: 'en', address: 'Vzorova 4, 110 00 Prague, Czechia', site: 'Prague store network', contact: 'compliance@acme-cz.example', fictional: true },
];

const supplierNames = [
  'Example Polymers GmbH',
  'Sample Foams Sp. z o.o.',
  'Demo Textiles AG',
  'Northwind Packaging Components B.V.',
];

const materialFamilies = ['paper_fibre','glass','aluminium','steel','PET','PE','PP','wood','textile','composite'];
const typeSequence = [
  ...Array(12).fill('sales'),
  ...Array(6).fill('grouped'),
  ...Array(6).fill('transport'),
  ...Array(4).fill('ecommerce'),
  ...Array(4).fill('reusable'),
];

function code(prefix, value) {
  return `ACME-${prefix}-${String(value).padStart(3, '0')}`;
}

// One scenario per supplier, so the demo shows a clean case, a missing document, an expired
// document with its replacement, and a rejected upload followed by a clean resubmission.
const supplierScenarios = [
  { scenario: 'complete_accepted', description: 'Complete, clean, accepted evidence' },
  { scenario: 'missing_recycled_content', description: 'Missing recycled-content evidence' },
  { scenario: 'expired_then_replaced', description: 'Expired declaration plus replacement evidence' },
  { scenario: 'mime_mismatch_then_clean', description: 'Rejected MIME-mismatched upload followed by a clean resubmission' },
];

export function createAcmeCatalog() {
  const suppliers = supplierNames.map((name, index) => ({
    id: code('SUP', index + 1),
    name,
    ...supplierScenarios[index],
    organizationId: acmeOrganizations[index].id,
    contact: `supplier${index + 1}@supplier.example`,
    fictional: true,
  }));
  const materials = Array.from({ length: 18 }, (_, index) => ({
    id: code('MAT', index + 1),
    name: `Synthetic material ${String(index + 1).padStart(2, '0')}`,
    family: materialFamilies[index % materialFamilies.length],
    recycledContentPct: index % 3 === 0 ? 35 : 45,
  }));
  const components = Array.from({ length: 40 }, (_, index) => ({
    id: code('CMP', index + 1),
    name: `Synthetic component ${String(index + 1).padStart(2, '0')}`,
    materialId: materials[index % materials.length].id,
    supplierId: suppliers[index % suppliers.length].id,
    massG: Number((8.5 + index * 0.75).toFixed(3)),
  }));
  const packaging = Array.from({ length: 32 }, (_, index) => {
    const componentIds = [components[index].id];
    if (index < 8) componentIds.push(components[index + 32].id);
    return {
      id: code('PKG', index + 1),
      name: `Synthetic packaging ${String(index + 1).padStart(2, '0')}`,
      packagingType: typeSequence[index],
      country: index % 4 === 0 ? 'DE' : index % 4 === 1 ? 'PL' : index % 4 === 2 ? 'FR' : 'CZ',
      supplierId: suppliers[index % suppliers.length].id,
      recycledContentPct: index === 1 ? 5 : index === 5 ? null : 40,
      bom: {
        id: code('BOM', index + 1),
        version: 1,
        lines: componentIds.map((componentId) => ({ componentId, quantity: 1, unit: 'piece' })),
      },
    };
  });
  return { suppliers, materials, components, packaging };
}

export function createAcmeValidJsonImport() {
  const catalog = createAcmeCatalog();
  return {
    schemaVersion: '1.0',
    suppliers: catalog.suppliers,
    materials: catalog.materials,
    components: catalog.components,
    packaging: catalog.packaging.slice(0, 28),
  };
}

export function createAcmeSupplementalCsv() {
  const rows = createAcmeCatalog().packaging.slice(28);
  const header = 'id,name,packagingType,country,supplierId,recycledContentPct,bomId,bomVersion,componentIds';
  return [header, ...rows.map((row) => [
    row.id,
    row.name,
    row.packagingType,
    row.country,
    row.supplierId,
    row.recycledContentPct ?? '',
    row.bom.id,
    row.bom.version,
    row.bom.lines.map((line) => line.componentId).join('|'),
  ].join(','))].join('\n');
}

export function createAcmeInvalidImport() {
  const catalog = createAcmeCatalog();
  const template = structuredClone(catalog.packaging[0]);
  const rows = Array.from({ length: 8 }, (_, index) => ({ ...structuredClone(template), id: `ACME-INVALID-${index + 1}`, bom: { ...structuredClone(template.bom), id: `ACME-INVALID-BOM-${index + 1}` } }));
  rows[0].id = '';
  rows[1].id = rows[2].id;
  rows[3].bom.lines[0].quantity = -1;
  rows[4].bom.lines[0].unit = 'unsupported';
  rows[5].bom.lines[0].componentId = 'ACME-MAT-UNKNOWN';
  rows[6].packagingType = 'invalid_type';
  rows[7].bom = null;
  return {
    schemaVersion: '0.0-unsupported',
    suppliers: catalog.suppliers,
    materials: catalog.materials,
    components: catalog.components,
    packaging: rows,
  };
}


export function createAcmeDataset() {
  const catalog = createAcmeCatalog();
  return {
    ...ACME_DATASET,
    disclaimer: ACME_DISCLAIMER,
    marker: ACME_FICTION_MARKER,
    organizations: acmeOrganizations,
    ...catalog,
    boms: catalog.packaging.map((item) => item.bom),
  };
}

// Stable key ordering so the JSON encoding — and therefore the checksum — does not depend
// on property insertion order.
function canonicalize(value) {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonicalize(value[key])]));
  return value;
}

export function canonicalAcmeJson(dataset = createAcmeDataset()) {
  return `${JSON.stringify(canonicalize(dataset), null, 2)}\n`;
}

export function acmeDatasetCounts(dataset = createAcmeDataset()) {
  return {
    organizations: dataset.organizations.length,
    suppliers: dataset.suppliers.length,
    packaging: dataset.packaging.length,
    materials: dataset.materials.length,
    components: dataset.components.length,
    boms: dataset.boms.length,
    validImportRows: createAcmeValidJsonImport().packaging.length,
    invalidImportRows: createAcmeInvalidImport().packaging.length,
  };
}

// The shape the Community demo and documentation both promise. Checked by the generator's
// validate command so the dataset cannot silently drift away from what is published.
export const ACME_EXPECTED_COUNTS = {
  organizations: 4, suppliers: 4, packaging: 32, materials: 18, components: 40, boms: 32, validImportRows: 28, invalidImportRows: 8,
};

export function validateAcmeDataset(dataset = createAcmeDataset()) {
  const problems = [];
  const counts = acmeDatasetCounts(dataset);
  for (const [key, expected] of Object.entries(ACME_EXPECTED_COUNTS)) {
    if (counts[key] !== expected) problems.push(`${key}: expected ${expected}, got ${counts[key]}`);
  }
  const ids = [...dataset.organizations, ...dataset.suppliers, ...dataset.materials, ...dataset.components, ...dataset.packaging].map((item) => item.id);
  const duplicates = ids.filter((id, index) => ids.indexOf(id) !== index);
  if (duplicates.length) problems.push(`duplicate identifiers: ${[...new Set(duplicates)].join(',')}`);
  if (ids.some((id) => !/^ACME-[A-Z]+-\d{3}$/.test(id))) problems.push('identifier does not follow the ACME-XXX-000 convention');
  const materialIds = new Set(dataset.materials.map((item) => item.id));
  const supplierIds = new Set(dataset.suppliers.map((item) => item.id));
  if (dataset.components.some((item) => !materialIds.has(item.materialId))) problems.push('component references an unknown material');
  if (dataset.components.some((item) => !supplierIds.has(item.supplierId))) problems.push('component references an unknown supplier');
  const componentIds = new Set(dataset.components.map((item) => item.id));
  if (dataset.packaging.some((item) => item.bom.lines.some((line) => !componentIds.has(line.componentId)))) problems.push('BOM line references an unknown component');
  const packagingTypes = new Set(dataset.packaging.map((item) => item.packagingType));
  for (const required of ['sales', 'grouped', 'transport', 'ecommerce', 'reusable']) {
    if (!packagingTypes.has(required)) problems.push(`packaging type not covered: ${required}`);
  }
  if (dataset.suppliers.length !== new Set(dataset.suppliers.map((item) => item.scenario)).size) problems.push('supplier scenarios are not distinct');
  return { valid: problems.length === 0, counts, problems };
}
